import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/lib/Providers";
import { useAppDispatch } from "@/redux/hooks";
import { onAuthStateChanged } from "firebase/auth";
import auth from "@/firebase/firebase.auth";
import { setUser } from "@/redux/features/user/userSlice";

export const metadata: Metadata = {
  title: "Best Services Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
